name: backend
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.4
  functions_framework: ^0.4.1
  core:
    path: ../core
dev_dependencies:
  build_runner: ^2.0.4
  functions_framework_builder: ^0.4.2
  pedantic: ^1.9.0
