name: core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  json_serializable: ^4.0.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
